import Head from "next/head";
import React from "react";
import app from "../../utils/axiosConfig";

export default function App() {
  const [{ author, error, quote }, setState] = React.useState({
    author: "",
    quote: "",
    error: "",
  });

  React.useEffect(() => {
    async function fetchQuote() {
      try {
        const res = await app.get("quote");

        setState({
          author: res.data.author,
          error: "",
          quote: res.data.quote,
        });
      } catch (error) {
        setState({
          author: "",
          error: error.toString(),
          quote: "",
        });
      }
    }

    fetchQuote();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <h1>Loaded Base Environment:</h1>
        <div data-testid="public-url" className="env">
          {process.env.NEXT_PUBLIC_BASEURL}
        </div>
        <h1>Loaded Specific Environment:</h1>
        <div data-testid="public-env" className="env">
          {process.env.NEXT_PUBLIC_ENV}
        </div>
        <h2>Environment Specific Quote:</h2>
        <div className="env">
          <span data-testid="quote">{quote}</span> -{" "}
          <i data-testid="author">{author}</i>
        </div>
        {error && (
          <p data-testid="error" className="error">
            {error}
          </p>
        )}
      </main>
    </>
  );
}
